version: '3'

services:
  nginx:
    build: ${PWD}/nginx
    container_name: nginx_csr
    ports:
      - 8002:80
    volumes:
      - ${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/nginx:/var/www/html
    depends_on:
      - ztsphp
    networks:
      default:
        ipv4_address: 172.31.0.2

  ztsphp:
    build: ${PWD}/ztsphp
    container_name: ztsphp_csr
    volumes:
      - ${PWD}/ztsphp:/var/www/html
    networks:
      default:
        ipv4_address: 172.31.0.3

  selenium-hub:
    image: selenium/hub:3.141.59-xenon
    container_name: selenium-hub
    ports:
      - 4444:4444
    networks:
      default:
        ipv4_address: 172.31.0.4

  chrome1:
    image: selenium/node-chrome-debug:3.141.59-xenon
    container_name: chrome1
    ports:
      - 5900:5900
    links:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      default:
        ipv4_address: 172.31.0.5

  chrome2:
    image: selenium/node-chrome-debug:3.141.59-xenon
    container_name: chrome2
    ports:
      - 5901:5900
    links:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      default:
        ipv4_address: 172.31.0.6

  # chrome3:
  #   image: selenium/node-chrome-debug:3.141.59-xenon
  #   container_name: chrome3
  #   ports:
  #     - 5902:5900
  #   links:
  #     - selenium-hub
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444
  #   networks:
  #     default:
  #       ipv4_address: 172.31.0.7

  # chrome4:
  #   image: selenium/node-chrome-debug:3.141.59-xenon
  #   container_name: chrome4
  #   ports:
  #     - 5903:5900
  #   links:
  #     - selenium-hub
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444
  #   networks:
  #     default:
  #       ipv4_address: 172.31.0.8

  # chrome5:
  #   image: selenium/node-chrome-debug:3.141.59-xenon
  #   container_name: chrome5
  #   ports:
  #     - 5904:5900
  #   links:
  #     - selenium-hub
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444
  #   networks:
  #     default:
  #       ipv4_address: 172.31.0.9

networks:
  default:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.31.0.0/16
